#!/bin/bash


g++ -o HF hartree-fock++.cc -std=c++11 -I/usr/local/libint/2.1.0-beta2/include -I/usr/local/libint/2.1.0-beta2/include/libint2 -I/home/vultor/PROGRAMAS/eigen-eigen-07105f7124f9 -L/usr/local/libint/2.1.0-beta2/lib/ -lint2 -DSRCDATADIR=\"/usr/local/libint/2.1.0-beta2/share/libint/2.1.0-beta2/basis\" -fopenmp




